export type NotificationTypes =
  | 'EMAIL'
  | 'SMS'
  | 'TEAMS_NOTIFICATION'
  | 'PUSH_NOTIFICATION'
  | 'IN_APP_NOTIFICATION';

export enum MessageTypes {
  'ADMIN_INVITE' = 'ADMIN_INVITE',
  'VERIFY_EMAIL' = 'VERIFY_EMAIL',
  'SEND_OTP' = 'SEND_OTP',
  'VERIFY_PHONE_OTP' = 'VERIFY_PHONE_OTP',
  'REGISTRATION_SUCCESSFUL' = 'REGISTRATION_SUCCESSFUL',
  'RESET_PASSWORD_EMAIL' = 'RESET_PASSWORD_EMAIL',
  'ORDER_CONFIRMATION_EMAIL' = 'ORDER_CONFIRMATION_EMAIL',
  'ORDER_CREATED_NOTIFICATION' = 'ORDER_CREATED_NOTIFICATION',
  'PAYMENT_RECEIVED_NOTIFICATION' = 'PAYMENT_RECEIVED_NOTIFICATION',
  'ORDER_FAILED_NOTIFICATION' = 'ORDER_FAILED_NOTIFICATION',
  'SUBSCRIPTION_EMAIL' = 'SUBSCRIPTION_EMAIL',
  'PRODUCT_AVAILABLE_EMAIL' = 'PRODUCT_AVAILABLE_EMAIL',
  'ORDER_DELIVERY_EMAIL' = 'ORDER_DELIVERY_EMAIL',
  'PRODUCT_AVAILABLE_INTEREST_EMAIL' = 'PRODUCT_AVAILABLE_INTEREST_EMAIL',
  'CONTACT_US' = 'CONTACT_US',
  'CONTACT_US_ADMIN' = 'CONTACT_US_ADMIN',
  'CREDIT_APPROVED' = 'CREDIT_APPROVED',
  'CREDIT_REJECTED' = 'CREDIT_REJECTED',
  'SHIPMENT_INITIATED' = 'SHIPMENT_INITIATED',
  'NEW_VOUCHER' = 'NEW_VOUCHER',
  'PASSWORD_RESET' = 'PASSWORD_RESET',
}

export interface MessageRecipient {
  userId?: string;
  email?: string;
  phoneNumber?: string;
}

export enum NotificationChannels {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  TEAMS_NOTIFICATION = 'TEAMS_NOTIFICATION',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
  IN_APP_NOTIFICATION = 'IN_APP_NOTIFICATION',
}

export enum EmailTemplateIds {
  VERIFY_EMAIL = 1,
  ORDER_CONFIRMATION_EMAIL = 2,
  PRODUCT_AVAILABLE_INTEREST_EMAIL = 3,
  CONTACT_US = 4,
  CONTACT_US_ADMIN = 5,
  ADMIN_INVITE = 6,
  PRODUCT_AVAILABLE_EMAIL = 7,

  SUBSCRIPTION_EMAIL = 8,
  ORDER_DELIVERY_EMAIL = 6,
  SHIPMENT_INITIATED = 9,
  NEW_VOUCHER = 10,
  PAYMENT_RECEIVED_NOTIFICATION = 11,
  CREDIT_APPROVED = 12,
  REGISTRATION_SUCCESSFUL = 13,
  RESET_PASSWORD_EMAIL = 14,

  CREDIT_REJECTED = 15,

  PASSWORD_RESET = 16,
}
